apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: furnishing
  namespace: argocd
spec:
  clusterResourceWhitelist:
  # Allow writing all types of Kubernetes resources
  - group: '*'
    kind: '*'
  destinations:
  # Allow to deploy to same cluster, all namespaces.
  - namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://charts.jetstack.io
  - https://kubernetes.github.io/ingress-nginx
  - ssh://git@github.com/squer-solutions/infrastructure-provisioning-workshop.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: furnishing
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: apps
  project: default
  source:
    repoURL: ssh://git@github.com/squer-solutions/infrastructure-provisioning-workshop.git
    targetRevision: level2
    path: _furnishing
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true